file_format: "1"
id: swoop
name: swoop
type: shield
url: https://github.com/jimmerricks/swoop
requires: [pro_micro]
exposes: []
features:
  - keys
  - encoders
siblings:
  - swoop_left
  - swoop_right
